language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t borkydog/docker-react -f Dockerfile.dev .

script:
  - docker-run -e CI=true borkydog/docker-react npm run test